
project_id = "zbrdfhgkffnbnthtjmxb"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[auth]
enabled = true

[storage]
enabled = true

[functions]
[functions.open-finance]
verify_jwt = true

[functions.market-data]
verify_jwt = true
