
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhimpyxzedzildagctpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoaW1weXh6ZWR6aWxkYWdjdHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDIyMzEsImV4cCI6MjA2MDMxODIzMX0.D_4bIstCI1Qspv_caes94z7HuWXRiZR-yi5OAPcc-Eg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
